name = "WraithSV"
uuid = "da1843e0-e922-40ae-9840-cb4a5d8973b4"
version = "1.0.0-DEV"
authors = ["pdimens <pdimens@gmail.com> and contributors"]

[deps]
XAM = "d759349c-bcba-11e9-07c2-5b90f8f05f7c"

[compat]
XAM = "0.4.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
